create table IF NOT EXISTS xmlFileStore(fileName varchar(100),content varchar(4000), description varchar(1000), STATUS varchar(100) );
create table IF NOT EXISTS USERS(USERNAME varchar(100),PASSWORD varchar(100), EMAIL varchar(100) ,STATUS varchar(100));
create table IF NOT EXISTS Person(id integer identity primary key , name varchar(100), gender varchar(1), dateOfBirth date, STATUS varchar(100));
CREATE TABLE PEOPLE (id BIGINT generated by default as identity, name VARCHAR(255), CREATED_DATE_TIME TIMESTAMP, PRIMARY KEY (id));
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;
insert into PEOPLE(id, name, CREATED_DATE_TIME) values ('1001', 'SASIKUMAR', NOW());
INSERT INTO USERS(USERNAME, PASSWORD, EMAIL) VALUES ('a', 'secret', 'spring-integration@awesome.com');
INSERT INTO USERS(USERNAME, PASSWORD, EMAIL) VALUES ('b', 's3cr3t', 'spring@rocks.com');
INSERT INTO USERS(USERNAME, PASSWORD, EMAIL) VALUES ('foo', 'bar', 'foo@bar.de');
INSERT INTO xmlFileStore (fileName, content, description) VALUES ('test.xml', '<test>', 'test')